### PR TITLE
Finalize `n_species`, deprecate/defunct other functions, add `CITATION.cff` 

### LINKED ISSUE #235: Remove `check_species()`, `get_scientific_name()`
_Suggested in camtraptor July 2023 coding sprint_

The functions `get_scientific_name()` returns a vector of scientific names for provided vernacular names, within the scope of a package. It does not allow scientific name values:

```R
> get_scientific_name(mica, c("bever", "mens"))
[1] "Castor fiber" "Homo sapiens"

> get_scientific_name(mica, c("bever", "mens", "Ardea")
+ )
Error: Invalid value for vernacular_name parameter: ardea.
Valid inputs are: mallard, gadwall, great herons, grey heron, eurasian beaver, human, beech marten, european polecat, red fox, wilde eend, krakeend, reigers, blauwe reiger, bever, mens, steenmarter, bunzing and vos.
```

The function `check_species()` returns a vector of scientific names for provided vernacular names _and_ scientific names, within the scope of a package:

```R
> check_species(mica, c("bever", "mens", "ardea"))
Scientific name of bever: Castor fiber
Scientific name of mens: Homo sapiens
[1] "Castor fiber" "Homo sapiens" "Ardea" 
```

We think these functions are no longer necessary:

- The current functions are confusing (what is their difference?)
- The current functions translate vernacular names to scientific names, but only based on the info that is available in a package. So one could not get a result because the species is not present or (worse) the species is present, but the vernacular name is not included.
- The suggested `taxonomy()` inbo/camtraptor#115 function provides an overview of taxa that are present in a (filtered) package in a **tabular format**. That information is easier to scan for existing (and missing) vernacular names that the current functions.
- The suggested `filter_` functions inbo/camtrapdp#23 allow to search on any column, e.g. `scientificName`, `vernacularName.nld` etc. Having functions that convert vernacular names to scientific names are less useful here.

### LINKED ISSUE #343: Deprecate `get_species()`
Replaced by reexported function `taxa()` from camtrapdp.

### LINKED ISSUE #345: Add `CITATION.cff`

### PR DESCRIPTION
**Pull request by damianooldoni**
This pull request includes several changes to the codebase, focusing on:
- finalizing `n_species()` and its tests
- deprecating some functions
- improving documentation

### Finalizing `n_species()` and its tests

Up to now, tests were not really taken into account as we were way far from getting the functions ready to the new format. From this PR we can start using them 🥳 as the very first function, `n_species()`, is ready! So, please run `devtools::test(filter = "n_species")` as check. Its related tests have been simplified without losing testing power. Notice that we only consider event based observations for the standard functions of camtraptor v1.0.0 (#332).

### Deprecation of functions

* Deprecated the `get_species()` function in favor of `taxa()` (fix #343)
* `get_scientific_name()` and `check_species()` functions are defunct in favor of `taxa()` (fix #235). So, `check_species()` and `get_scientific_name()` functions are moved to `defunct.R`.

## Metadata

* Added `CITATION.cff` (fix #345) (using `cffr::cff_write()`).

### Documentation updates

* Updated references in multiple R files to inherit arg description from `n_species` instead of the deprecated `get_species`. This has been done by using `@inheritParams n_species` instead of `@inheritParams get_n_species`.
* Updated the `NEWS.md` file to reflect the deprecation/defunct of several functions, the introduction of new replacements and new citation file.

### Other code improvements

* Simplified `get_n_individuals()` and `get_n_obs()` functions by removing the `species` parameter and associated logic: we do not filter anymore within such functions, only via `filter_observations()`. **IMPORTANT**: these functions are still not finalized and do not follow the new data standard still. So, they will fail or return a non tested result.

### CODE REVIEW

File: R/n_species.R [hunk 1]
```diff
@@ -21,8 +24,9 @@ n_species <- function(x) {
   # Check camera trap data package
   camtrapdp::check_camtrapdp(x)
   
-  # Extract observations and deployments
-  observations <- observations(x)
+  # Extract event-based observations and deployments
+  observations <- observations(x) %>%
```
Comment (sannegovaert) [inline R/n_species.R:28]: I suggest:
`x <- filter_observations(.data$observationLevel == "event")` 
and using `observations(x)` instead of `observations`.

Because what if there is a deployment with only media-based observations?
It would now not be noticed in L33: `deployments_no_obs <- get_dep_no_obs(x)`.

And last, why is the count reduced by NA-values in a mutate-function, and not like this?:
 ```
n_species <-
    species %>% 
    dplyr::filter(!is.na(.data$scientificName)) %>% 
    dplyr::group_by(.data$deploymentID) %>%
    dplyr::count() %>%
    dplyr::ungroup()
```

**Review by sannegovaert — CHANGES_REQUESTED** [review]
Nice!
I have  1 remark about filtering on observationLevel & a suggestion for simplification.

File: R/n_species.R (hunk 1 above)
Comment (damianooldoni) [reply R/n_species.R]: Fully agree with first suggestion 🔝  Implemented in 28ae966 and 328a573.
About the reason why I use a mutate to not count NA as species: I agreed with you at the beginning , but then thanks to a failing test (A perfect example of the need of unit-tests!) I found the reason I wrote that few years ago 😄 We need to assign 0 to deployments with ONLY unidentified species (`scientificName` = `NA`). To do that, the shortest way I found was to do a standard `group_by() %>% count()` and then reducing the sum by one. I improved the comments in the code to better understand this for future-me and everybody else.

**Comment by damianooldoni** [comment]
I also ordered the output by using the original order as provided in deployment table. Tests added to check this.

Also added a test to check that deployments without event-based observations have `n = NA` as for deployments without any observation at all.

**Review by sannegovaert — APPROVED** [review]
Well done, I have no comments!
